export {default as Dashboard} from './Dashboard'
export {default as Products} from './Products/Products'
export {default as CreateProduct} from './Products/CreateProduct'
export {default as UpdateProduct} from './Products/UpdateProduct'
export {default as Users} from './Users/Users'
export {default as CreateUser} from './Users/CreateUser'
export {default as UpdateUser} from './Users/UpdateUser'
